version: '3'


services:
db:
image: mariadb:10.6
restart: always
command: --transaction-isolation=READ-COMMITTED --log-bin=ROW
volumes:
- db:/var/lib/mysql
environment:
- MYSQL_ROOT_PASSWORD=COK_GIZLI_ROOT_SIFRESI
- MYSQL_PASSWORD=GIZLI_KULLANICI_SIFRESI
- MYSQL_DATABASE=nextcloud
- MYSQL_USER=nextcloud


app:
image: nextcloud:latest
restart: always
ports:
- 8080:80
links:
- db
depends_on:
- db
volumes:
- nextcloud:/var/www/html
environment:
- MYSQL_PASSWORD=GIZLI_KULLANICI_SIFRESI
- MYSQL_DATABASE=nextcloud
- MYSQL_USER=nextcloud
- MYSQL_HOST=db


volumes:
nextcloud:
db:
